INSERT INTO categories (category) 
VALUES  ('Meditation'), 
        ('Nature'), 
        ('Movement'), 
        ('Social Connection'), 
        ('Self Expression');

INSERT INTO tasks (task, category_id)
VALUES  ('5 minute meditation', 1),
        ('10 minute meditation', 1),
        ('20 minute meditation', 1),
        ('30 minute meditation', 1),
        ('Yoga', 1),
        ('Take a walk in the park', 2),
        ('Hike a nature trail', 2),
        ('Plant in garden', 2),
        ('Add plant to home space', 2),
        ('Visit the beach', 2),
        ('Visit the river', 2),
        ('Dance', 3),
        ('Take a walk', 3),
        ('Yoga', 3),
        ('Exercise', 3),
        ('Join a group, eg. Meetup.com, ERG at work', 4),
        ('Attend a group activity', 4),
        ('Volunteer with an organization', 4),
        ('Make a new acquaintance or friend', 4),
        ('Reach out to family or friend', 4),
        ('Spend time with family or friend', 4),
        ('Support a family or friend', 4),
        ('Journaling', 5),
        ('Art', 5),
        ('Music', 5),
        ('Cognitive puzzle, eg. sudoku, crosswords, puzzle', 5),
        ('Act of kindness', 5);